# Site settings
title: BlockchainUniversity
description: A brief description of your site
url: "https://blockchainuniversityedu.github.io" # The base hostname & protocol for your site

# Build settings
theme: null # Disable theme if not using any
markdown: kramdown # The Markdown parser/renderer
plugins:
  - jekyll-feed # Plugin for generating an Atom feed for your site

# Permalinks
permalink: /:title/ # URL structure for posts and pages

# Exclude files from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Development settings
baseurl: "" # The subpath of your site, e.g., /blog

# Pagination settings
paginate: 5 # Number of posts per page for pagination

# SEO settings
meta_description: "Your site's meta description"

source: docs
